/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as RecognizeRouteImport } from './routes/recognize'
import { Route as ApiRecognizeRouteImport } from './routes/api/recognize'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const RecognizeRoute = RecognizeRouteImport.update({
  id: '/recognize',
  path: '/recognize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecognizeRoute = ApiRecognizeRouteImport.update({
  id: '/api/recognize',
  path: '/api/recognize',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/recognize': typeof RecognizeRoute
  '/api/recognize': typeof ApiRecognizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/recognize': typeof RecognizeRoute
  '/api/recognize': typeof ApiRecognizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/recognize': typeof RecognizeRoute
  '/api/recognize': typeof ApiRecognizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/history' | '/recognize' | '/api/recognize'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/history' | '/recognize' | '/api/recognize'
  id: '__root__' | '/' | '/about' | '/history' | '/recognize' | '/api/recognize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HistoryRoute: typeof HistoryRoute
  RecognizeRoute: typeof RecognizeRoute
  ApiRecognizeRoute: typeof ApiRecognizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recognize': {
      id: '/recognize'
      path: '/recognize'
      fullPath: '/recognize'
      preLoaderRoute: typeof RecognizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recognize': {
      id: '/api/recognize'
      path: '/api/recognize'
      fullPath: '/api/recognize'
      preLoaderRoute: typeof ApiRecognizeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HistoryRoute: HistoryRoute,
  RecognizeRoute: RecognizeRoute,
  ApiRecognizeRoute: ApiRecognizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
